package handlers

import (
	"context"
	"fmt"
	"net/http"

	"github.com/auto-developer-orchestrator/backend/internal/git"
	"github.com/auto-developer-orchestrator/backend/internal/pi"
	"go.uber.org/zap"
)

// postCompletion runs after Pi finishes a task: commits changes, pushes branch, creates PR.
// If autoMerge is true, merges the PR back to master after creation.
func (h *PiHandler) postCompletion(
	ctx context.Context,
	projectPath string,
	branchName string,
	promptMessage string,
	autoMerge bool,
	w http.ResponseWriter,
	canFlush bool,
	flusher http.Flusher,
) {
	// 1. Check for uncommitted changes
	status, err := h.git.Status(ctx, git.StatusOptions{Dir: projectPath})
	if err != nil {
		h.log.Warn("postCompletion: git status failed", zap.Error(err))
		return
	}
	if status.IsClean {
		h.log.Info("postCompletion: working tree clean, nothing to commit")
		return
	}

	h.log.Info("postCompletion: detected changes",
		zap.Strings("modified", status.Modified),
		zap.Strings("added", status.Added),
		zap.Strings("deleted", status.Deleted),
	)

	// 2. Commit
	commitMsg := fmt.Sprintf("feat: %s\n\nImplemented by Pi agent.", truncateStr(promptMessage, 72))
	if err := h.git.Commit(ctx, git.CommitOptions{
		Dir:     projectPath,
		Message: commitMsg,
		Author:  "Pi Agent",
		Email:   "pi@orchestrator.local",
	}); err != nil {
		h.log.Error("postCompletion: git commit failed", zap.Error(err))
		writeSSE(w, pi.EventError, map[string]string{"error": fmt.Sprintf("commit failed: %v", err)}, canFlush, flusher)
		return
	}
	writeSSE(w, pi.EventCommitCreated, map[string]string{
		"message": commitMsg,
		"branch":  branchName,
	}, canFlush, flusher)

	// 3. Push
	if err := h.git.Push(ctx, git.PushOptions{
		Dir:    projectPath,
		Branch: branchName,
	}); err != nil {
		h.log.Error("postCompletion: git push failed", zap.Error(err))
		writeSSE(w, pi.EventError, map[string]string{"error": fmt.Sprintf("push failed: %v", err)}, canFlush, flusher)
		return
	}
	writeSSE(w, pi.EventPushComplete, map[string]string{
		"branch": branchName,
	}, canFlush, flusher)

	// 4. Parse owner/repo from remote
	remoteURL, err := h.git.GetRemoteURL(ctx, projectPath)
	if err != nil {
		h.log.Warn("postCompletion: no remote URL", zap.Error(err))
		return
	}
	owner, repo, err := parseOwnerRepo(remoteURL)
	if err != nil {
		h.log.Warn("postCompletion: cannot parse remote", zap.Error(err))
		return
	}

	// 5. Create PR via GitHub API
	if h.github == nil {
		h.log.Warn("postCompletion: no GitHub handler, skipping PR creation")
		return
	}

	title := fmt.Sprintf("Pi: %s", truncateStr(promptMessage, 60))
	prBody := fmt.Sprintf("## Summary\n%s\n\n---\n*Auto-generated by Pi Agent*", promptMessage)
	prResult, err := h.github.CreatePR(owner, repo, title, prBody, branchName, "master")
	if err != nil {
		h.log.Error("postCompletion: PR creation failed", zap.Error(err))
		writeSSE(w, pi.EventError, map[string]string{"error": fmt.Sprintf("PR creation failed: %v", err)}, canFlush, flusher)
		return
	}

	prURL, _ := prResult["html_url"].(string)
	prNum := 0
	if num, ok := prResult["number"].(float64); ok {
		prNum = int(num)
	}
	writeSSE(w, pi.EventPRCreated, map[string]interface{}{
		"url":    prURL,
		"number": prNum,
		"title":  title,
	}, canFlush, flusher)

	h.log.Info("postCompletion: PR created",
		zap.String("url", prURL),
		zap.Int("number", prNum),
	)

	// Auto-merge if requested
	if autoMerge && prNum > 0 && h.github != nil {
		mergeResult, err := h.github.MergePR(owner, repo, prNum, "Pi auto-merge")
		if err != nil {
			h.log.Warn("postCompletion: auto-merge failed", zap.Error(err))
			writeSSE(w, "error", map[string]string{"error": fmt.Sprintf("auto-merge failed: %v", err)}, canFlush, flusher)
			return
		}

		mergeSHA, _ := mergeResult["sha"].(string)
		writeSSE(w, "pr_merged", map[string]interface{}{
			"prNumber": prNum,
			"sha":      mergeSHA,
		}, canFlush, flusher)

		// Checkout master and pull latest
		if err := h.git.Checkout(ctx, git.CheckoutOptions{
			Dir:    projectPath,
			Branch: "master",
		}); err != nil {
			h.log.Warn("postCompletion: checkout master failed", zap.Error(err))
		}
		if err := h.git.Pull(ctx, git.PullOptions{Dir: projectPath}); err != nil {
			h.log.Warn("postCompletion: pull master failed", zap.Error(err))
		}

		h.log.Info("postCompletion: PR auto-merged",
			zap.Int("pr", prNum),
			zap.String("sha", mergeSHA),
		)
	}
}
