#!/usr/bin/env bash
# deep-research-engine bootstrap — host-side, idempotent.
#
# Brings up the org's sandbox container and verifies host-side deps
# (SurrealDB, optional MCP servers). Safe to re-run.
#
# What this does NOT do: ingest data, run the pipeline, or write to the
# graph. Those are agent-side operations driven by skills like
# CONTEXT_ENGINE.md and INGEST_STRUCTURED_EXPORT.md. This script just gets
# the container running and reachable.
#
# Usage:
#   ./bootstrap.sh                # full bootstrap
#   ./bootstrap.sh --check        # verify only, don't start anything
#   ./bootstrap.sh --down         # tear down what bootstrap brought up

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Canonical Pux mount + label — lets Pux adopt this container instead of
# spinning up a sibling. See [[feedback_container_reuse_label_discovery]].
export OPENSHELL_PROJECT_PATH="${OPENSHELL_PROJECT_PATH:-$SCRIPT_DIR}"

log()  { printf '[bootstrap] %s\n' "$*"; }
ok()   { printf '[bootstrap] ✓ %s\n' "$*"; }
err()  { printf '[bootstrap] ERROR: %s\n' "$*" >&2; }

CHECK_ONLY=0
DO_DOWN=0
case "${1:-}" in
  --check) CHECK_ONLY=1 ;;
  --down)  DO_DOWN=1 ;;
  "") ;;
  *) err "unknown arg: $1"; exit 1 ;;
esac

# --down: inverse of up. Named volumes preserved (no -v).
# To wipe volumes too, run `docker compose down -v` manually.
if [ "$DO_DOWN" = "1" ]; then
  log "tearing down (docker compose down)"
  docker compose down
  ok "containers stopped"
  exit 0
fi

# 1. Host-side SurrealDB — the org's persistence layer.
SURREALDB_HEALTH="${SURREALDB_HEALTH:-http://localhost:8000/surreal/health}"
log "checking SurrealDB at $SURREALDB_HEALTH"
if curl -sf -o /dev/null "$SURREALDB_HEALTH"; then
  ok "SurrealDB reachable"
else
  err "SurrealDB not reachable at $SURREALDB_HEALTH"
  err "start it on the host first (e.g. via shared-docker-infra compose)"
  exit 1
fi

# 2. Optional MCP servers — soft checks (warn only).
MEDIA_MCP_URL="${MEDIA_MCP_URL:-http://localhost:8101}"
WEB_MCP_URL="${WEB_MCP_URL:-http://localhost:8327}"
for url in "$MEDIA_MCP_URL" "$WEB_MCP_URL"; do
  if curl -sf -o /dev/null --max-time 2 "$url"; then
    ok "MCP server reachable: $url"
  else
    log "warning: MCP server not reachable: $url (multimodal ingest paths may degrade)"
  fi
done

if [ "$CHECK_ONLY" = "1" ]; then
  log "--check requested; not starting container"
  exit 0
fi

# 3. Detect gVisor (runsc) availability. The auto-generated compose requests
#    `runtime: runsc` because org.toml declares runtime_class = "gvisor".
#    Hosts without runsc installed choke on that line. Write a local
#    override that strips it when missing. The override is gitignored.
if ! docker info 2>/dev/null | grep -qi 'runtimes:.*runsc'; then
  log "runsc not installed locally — writing docker-compose.override.yml to neutralize runtime line"
  cat > docker-compose.override.yml <<'EOF'
# Local override — strips `runtime: runsc` for hosts without gVisor.
# Auto-generated by bootstrap.sh; safe to delete.
services:
  deep-research-engine-sandbox:
    runtime: ""
EOF
fi

# 4. Bring up the sandbox container.
log "starting sandbox (docker compose up -d)"
docker compose up -d

# 5. Wait for running state.
log "waiting for container to be running"
for i in $(seq 1 30); do
  if docker compose ps --status running --quiet | grep -q .; then
    ok "container running after ${i}s"
    break
  fi
  sleep 1
done

# 6. Smoke test: sandbox can reach SurrealDB from inside the container.
#    The compose file uses `network_mode: host`, so the container shares the
#    host's network namespace and reaches SurrealDB on localhost. The env
#    var SURREALDB_URL still names host.docker.internal (for bridged-mode
#    portability); inside host-mode containers we substitute localhost.
CONTAINER="deep-research-engine-sandbox"
log "smoke test: container → SurrealDB"
if docker compose exec -T "$CONTAINER" \
    python3 -c "import os,urllib.request; url=os.environ['SURREALDB_URL'].replace('host.docker.internal','localhost'); urllib.request.urlopen(url+'/health').read(); print('ok')" \
    >/dev/null 2>&1; then
  ok "container → SurrealDB reachable"
else
  err "container cannot reach SurrealDB — check network_mode + SurrealDB health"
  exit 1
fi

echo
echo "═══════════════════════════════════════════════════════════════"
echo "  deep-research-engine bootstrap — COMPLETE"
echo "═══════════════════════════════════════════════════════════════"
echo "  Container:  $CONTAINER (restart: unless-stopped)"
echo "  SurrealDB:  $SURREALDB_HEALTH"
echo "  Workspace:  $SCRIPT_DIR  (bind-mounted at /sandbox/workspace)"
echo
echo "  Next steps (agent-side):"
echo "    fire a prompt with --org deep-research-engine"
echo "    the agent will read CONTEXT_ENGINE.md + INGEST_STRUCTURED_EXPORT.md"
echo "═══════════════════════════════════════════════════════════════"
