#!/usr/bin/env python3
"""
scripts.py — kernel-default script manager.

Gives the agent a self-evolving toolkit: write small Python scripts,
run them by name, list what exists, edit iteratively. Scripts persist
in /sandbox/workspace/scripts/ (project-scoped, survives sandbox restarts).

Why this exists:
  Pre-baked tools cover the 80% case but break when selectors change.
  Bash + file_write is too low-level for the LLM to use efficiently.
  This is the middle layer: a structured place for ad-hoc Python that
  the agent writes once and calls many times.

Usage:
  python3 scripts.py --make --name <name> --desc "<description>" --code "<code>"
  python3 scripts.py --run  --name <name> [--args arg1 arg2 ...]
  python3 scripts.py --list
  python3 scripts.py --edit --name <name> --code "<new code>"
  python3 scripts.py --show --name <name>
  python3 scripts.py --rm   --name <name>

All output is JSON. Errors return exit code 1 with {"error": "..."}.
"""
import argparse
import ast
import json
import os
import re
import subprocess
import sys
import textwrap
from datetime import datetime
from pathlib import Path

SCRIPTS_DIR = Path("/sandbox/workspace/scripts")
TIMEOUT_DEFAULT = 300  # 5 min
TIMEOUT_MAX = 1800     # 30 min hard cap
OUTPUT_MAX = 50000     # 50k chars per stream


def _ensure_dir() -> Path:
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    return SCRIPTS_DIR


def _script_path(name: str) -> Path:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        raise ValueError(
            f"invalid script name '{name}': must match [A-Za-z_][A-Za-z0-9_]*"
        )
    return SCRIPTS_DIR / f"{name}.py"


def _extract_description(path: Path) -> str:
    """Pull the first line of the module docstring as a description."""
    try:
        text = path.read_text()
        tree = ast.parse(text)
        if (tree.body and isinstance(tree.body[0], ast.Expr)
                and isinstance(tree.body[0].value, ast.Constant)
                and isinstance(tree.body[0].value.value, str)):
            doc = tree.body[0].value.value.strip()
            return doc.split("\n")[0][:200]
    except Exception:
        pass
    return ""


def _validate_python(code: str) -> str | None:
    """Return error string if code doesn't parse, else None."""
    try:
        ast.parse(code)
        return None
    except SyntaxError as e:
        return f"line {e.lineno}: {e.msg}"


def make_script(name: str, description: str, code: str, overwrite: bool = False) -> dict:
    _ensure_dir()
    path = _script_path(name)

    if path.exists() and not overwrite:
        return {
            "error": f"script '{name}' already exists. Use --edit to modify, or --rm first.",
            "existing_path": str(path),
        }

    syntax_err = _validate_python(code)
    if syntax_err:
        return {"error": f"Python syntax error: {syntax_err}", "name": name}

    # Build the file: docstring header (first line = description) + code
    if description:
        docstring = f'"""\n{description}\n\nAuto-generated by agent on {datetime.now().isoformat(timespec="seconds")}.\n"""\n\n'
    else:
        docstring = ""
    full = docstring + code.rstrip() + "\n"

    path.write_text(full)
    return {
        "created": str(path),
        "name": name,
        "description": description,
        "lines": full.count("\n"),
    }


def run_script(name: str, args: list[str] | None = None, timeout: int = TIMEOUT_DEFAULT) -> dict:
    path = _script_path(name)
    if not path.exists():
        return {"error": f"script '{name}' not found. Use --list to see available scripts.", "name": name}

    cmd = [sys.executable, "-u", str(path)] + (args or [])
    timeout = max(1, min(timeout, TIMEOUT_MAX))

    # Make /sandbox/ importable so scripts can `from twitter_helpers import ...`,
    # `from session import ...`, etc. — these are the org-shipped helper modules.
    env = os.environ.copy()
    existing_path = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = "/sandbox:" + existing_path if existing_path else "/sandbox"

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(SCRIPTS_DIR),
            env=env,
        )
    except subprocess.TimeoutExpired:
        return {
            "error": f"execution timed out after {timeout}s",
            "name": name,
            "stdout_tail": "",
        }
    except Exception as e:
        return {"error": f"failed to launch: {e}", "name": name}

    # Tail output to avoid flooding the agent's context
    stdout = result.stdout[-OUTPUT_MAX:] if result.stdout else ""
    stderr = result.stderr[-OUTPUT_MAX:] if result.stderr else ""

    out = {
        "name": name,
        "exit_code": result.returncode,
        "success": result.returncode == 0,
        "stdout": stdout,
    }
    if stderr:
        out["stderr"] = stderr
    return out


def list_scripts() -> dict:
    _ensure_dir()
    scripts = []
    for path in sorted(SCRIPTS_DIR.glob("*.py")):
        scripts.append({
            "name": path.stem,
            "description": _extract_description(path),
            "size": path.stat().st_size,
            "modified": datetime.fromtimestamp(path.stat().st_mtime).isoformat(timespec="seconds"),
        })
    return {"scripts": scripts, "count": len(scripts), "dir": str(SCRIPTS_DIR)}


def edit_script(name: str, code: str, description: str | None = None) -> dict:
    """Replace the code of an existing script. Keeps description unless new one given."""
    path = _script_path(name)
    if not path.exists():
        return {"error": f"script '{name}' not found. Use --make to create it first.", "name": name}

    syntax_err = _validate_python(code)
    if syntax_err:
        return {"error": f"Python syntax error: {syntax_err}", "name": name}

    # Use provided description, else extract from existing file, else empty
    if description is None:
        description = _extract_description(path)

    if description:
        docstring = f'"""\n{description}\n\nUpdated by agent on {datetime.now().isoformat(timespec="seconds")}.\n"""\n\n'
    else:
        docstring = ""
    full = docstring + code.rstrip() + "\n"

    path.write_text(full)
    return {
        "updated": str(path),
        "name": name,
        "description": description,
        "lines": full.count("\n"),
    }


def show_script(name: str) -> dict:
    path = _script_path(name)
    if not path.exists():
        return {"error": f"script '{name}' not found", "name": name}
    return {
        "name": name,
        "description": _extract_description(path),
        "code": path.read_text(),
        "size": path.stat().st_size,
    }


def remove_script(name: str) -> dict:
    path = _script_path(name)
    if not path.exists():
        return {"error": f"script '{name}' not found", "name": name}
    path.unlink()
    return {"removed": str(path), "name": name}


def main():
    p = argparse.ArgumentParser(description="Script manager — write/run/list small Python helpers")
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--make", action="store_true", help="Create a new script")
    group.add_argument("--run", action="store_true", help="Run an existing script")
    group.add_argument("--list", action="store_true", help="List all scripts")
    group.add_argument("--edit", action="store_true", help="Replace code of an existing script")
    group.add_argument("--show", action="store_true", help="Print full source of a script")
    group.add_argument("--rm", action="store_true", help="Delete a script")

    p.add_argument("--name", help="Script name (snake_case)")
    p.add_argument("--desc", help="One-line description (used in --list output)")
    p.add_argument("--code", help="Python source code. For multi-line, use heredoc or pass via stdin.")
    p.add_argument("--args", nargs="*", default=[], help="Arguments to pass to --run")
    p.add_argument("--timeout", type=int, default=TIMEOUT_DEFAULT, help=f"Run timeout in seconds (default {TIMEOUT_DEFAULT}, max {TIMEOUT_MAX})")
    p.add_argument("--stdin", action="store_true", help="Read --code or --make code from stdin")

    args = p.parse_args()

    code = args.code
    if args.stdin:
        code = sys.stdin.read()

    if args.make:
        if not args.name or not code:
            print(json.dumps({"error": "--make requires --name and --code (or --stdin)"}))
            sys.exit(1)
        result = make_script(args.name, args.desc or "", code)
    elif args.run:
        if not args.name:
            print(json.dumps({"error": "--run requires --name"}))
            sys.exit(1)
        result = run_script(args.name, args.args, args.timeout)
    elif args.list:
        result = list_scripts()
    elif args.edit:
        if not args.name or not code:
            print(json.dumps({"error": "--edit requires --name and --code (or --stdin)"}))
            sys.exit(1)
        result = edit_script(args.name, code, args.desc)
    elif args.show:
        if not args.name:
            print(json.dumps({"error": "--show requires --name"}))
            sys.exit(1)
        result = show_script(args.name)
    elif args.rm:
        if not args.name:
            print(json.dumps({"error": "--rm requires --name"}))
            sys.exit(1)
        result = remove_script(args.name)

    print(json.dumps(result, indent=2))
    sys.exit(0 if "error" not in result else 1)


if __name__ == "__main__":
    main()
