#!/usr/bin/env python3
"""Cookie bridge: extract cookies from a Brave browser → inject into sandbox Chrome.

Two modes:

  EXTRACT ONLY (run on the Brave host or via SSH):
    python3 brave_cookie_bridge.py extract --domain youtube.com --out /tmp/yt-cookies.json
    python3 brave_cookie_bridge.py extract --domain youtube.com --netscape /tmp/yt-cookies.txt

  FULL BRIDGE (run from orchestrator host with SSH access to the Brave host):
    python3 brave_cookie_bridge.py bridge --domain youtube.com
      → extracts from Brave on the remote host, injects into sandbox Chrome

The extract mode uses browser_cookie3 to read the Flatpak Brave cookie DB
(decrypts AES-256-GCM values via the GNOME keyring key in Local State).

The bridge mode SSHs to $BRAVE_SSH_HOST, runs extract, and POSTs the
cookies to the sandbox sb_server's /cookies endpoint via docker exec.

Environment:
  BRAVE_SSH_HOST    SSH destination for the Brave host (bridge mode).
                    Default: user@brave-host (set this to your real host).
  SB_CONTAINER      Sandbox container name. Default: orchestrator-sandbox-mcp-default.

Cookie format matches sb_server's /cookies set contract:
  {name, value, domain, path, secure, expires, httponly}
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Flatpak Brave paths ──────────────────────────────────────────────────

BRAVE_BASE = "~/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser"
BRAVE_COOKIE_DB = f"{BRAVE_BASE}/Default/Cookies"
BRAVE_LOCAL_STATE = f"{BRAVE_BASE}/Local State"

SSH_HOST = os.environ.get("BRAVE_SSH_HOST", "user@brave-host")
CONTAINER = os.environ.get("SB_CONTAINER", "orchestrator-sandbox-mcp-default")
SB_PORT = 9876  # in-container sb_server port


# ── Extract ──────────────────────────────────────────────────────────────

def extract_cookies(domain: str, browser: str = "brave") -> list[dict]:
    """Extract cookies for domain from the browser's cookie DB.

    Returns list of {name, value, domain, path, secure, expires, httponly} dicts.
    """
    import browser_cookie3 as bc3

    cookie_file = os.path.expanduser(BRAVE_COOKIE_DB)
    key_file = os.path.expanduser(BRAVE_LOCAL_STATE)

    if not os.path.exists(cookie_file):
        raise FileNotFoundError(f"Cookie DB not found: {cookie_file}")

    kwargs = {"cookie_file": cookie_file, "key_file": key_file}
    if domain:
        kwargs["domain_name"] = domain

    fn = getattr(bc3, browser, None)
    if fn is None:
        raise ValueError(f"Unknown browser: {browser}")

    cj = fn(**kwargs)
    cookies = []
    for c in cj:
        rest = getattr(c, "_rest", {}) or {}
        cookies.append({
            "name": c.name,
            "value": c.value,
            "domain": c.domain,
            "path": c.path,
            "secure": bool(getattr(c, "secure", False)),
            "expires": getattr(c, "expires", None),
            "httponly": bool(rest.get("HttpOnly", False)),
        })
    return cookies


def write_json(cookies: list[dict], domain: str, out_path: str | None = None) -> str:
    """Write cookies as JSON (sb_server /restore_session + /cookies set format)."""
    payload = {
        "cookies": cookies,
        "localStorage": {},
        "url": f"https://{domain}",
        "saved_at": datetime.now(timezone.utc).isoformat(),
        "source": "brave",
        "domain": domain,
    }
    if out_path:
        Path(out_path).write_text(json.dumps(payload, indent=2))
        return out_path
    return json.dumps(payload, indent=2)


def write_netscape(cookies: list[dict], out_path: str) -> str:
    """Write cookies in Netscape format (yt-dlp --cookies compatible)."""
    lines = ["# Netscape HTTP Cookie File", "# This is generated by brave_cookie_bridge.py"]
    for c in cookies:
        # Netscape format: domain, include_subdomain, path, secure, expires, name, value
        domain = c["domain"]
        include_subdomain = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c["secure"] else "FALSE"
        expires = str(c["expires"] or 0)
        lines.append("\t".join([
            domain, include_subdomain, c["path"], secure, expires,
            c["name"], c["value"],
        ]))
    Path(out_path).write_text("\n".join(lines) + "\n")
    return out_path


# ── Bridge (SSH extract → sandbox inject) ────────────────────────────────

def ssh_extract(domain: str, host: str = SSH_HOST) -> list[dict]:
    """SSH to host, extract cookies, return as list of dicts."""
    # Serialize the extract function as a remote Python script
    remote_script = f'''
import json, sys
sys.path.insert(0, os.path.expanduser("~/.local/lib/python3.12/site-packages"))
import os
import browser_cookie3 as bc3

cookie_file = os.path.expanduser("{BRAVE_BASE}/Default/Cookies")
key_file = os.path.expanduser("{BRAVE_BASE}/Local State")

cj = bc3.brave(cookie_file=cookie_file, key_file=key_file, domain_name="{domain}")
cookies = []
for c in cj:
    rest = getattr(c, "_rest", {{}}) or {{}}
    cookies.append({{
        "name": c.name, "value": c.value, "domain": c.domain,
        "path": c.path, "secure": bool(getattr(c, "secure", False)),
        "expires": getattr(c, "expires", None),
        "httponly": bool(rest.get("HttpOnly", False)),
    }})
print(json.dumps(cookies))
'''
    # Fix the os import ordering
    remote_script = "import os\n" + remote_script

    result = subprocess.run(
        ["ssh", "-o", "ConnectTimeout=5", host, f"python3 -c '{remote_script}'"],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(f"SSH extract failed: {result.stderr.strip()}")
    return json.loads(result.stdout.strip())


def inject_into_sandbox(cookies: list[dict], container: str = CONTAINER, port: int = SB_PORT) -> dict:
    """POST cookies to the sandbox sb_server's /cookies endpoint.

    If the browser isn't open (sb is None), sb_server's /cookies hangs.
    Fall back to writing the session file so twitter_post.py can inject
    them via SeleniumBase on its next run.
    """
    payload = json.dumps({"action": "set", "cookies": cookies})
    try:
        # Use docker exec + curl to reach sb_server inside the container
        result = subprocess.run(
            ["docker", "exec", container, "curl", "-s", "-X", "POST",
             f"http://localhost:{port}/cookies",
             "-H", "Content-Type: application/json",
             "-d", payload],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0 and result.stdout:
            return json.loads(result.stdout)
    except subprocess.TimeoutExpired:
        pass  # Browser not open — fall through to file-based injection

    # Fallback: write session file directly into the container
    from datetime import datetime, timezone
    session_payload = json.dumps({
        "cookies": cookies,
        "localStorage": {},
        "url": "https://x.com",
        "saved_at": datetime.now(timezone.utc).isoformat(),
        "source": "brave-ssh-bridge",
        "domain": "x.com",
    })
    subprocess.run(
        ["docker", "exec", container, "bash", "-c",
         f'mkdir -p /sandbox/workspace/data && echo \'{session_payload}\' > /sandbox/workspace/data/.twitter-session.json'],
        capture_output=True, text=True, timeout=10,
    )
    return {"restored": True, "method": "session_file", "cookies": len(cookies)}


# ── CLI ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Cookie bridge: Brave → sandbox Chrome",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Extract YouTube cookies from Brave on this machine
  %(prog)s extract --domain youtube.com --out /tmp/yt-cookies.json

  # Extract as Netscape format for yt-dlp
  %(prog)s extract --domain youtube.com --netscape /tmp/yt-cookies.txt

  # Full bridge: SSH to the Brave host, extract, inject into sandbox
  # (set BRAVE_SSH_HOST or pass --host)
  %(prog)s bridge --domain youtube.com

  # Check what domains Brave has cookies for
  %(prog)s list-domains
        """,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_extract = sub.add_parser("extract", help="Extract cookies from local Brave")
    p_extract.add_argument("--domain", required=True, help="Cookie domain (e.g. youtube.com)")
    p_extract.add_argument("--out", help="JSON output path (default: stdout)")
    p_extract.add_argument("--netscape", help="Netscape output path (for yt-dlp --cookies)")

    p_bridge = sub.add_parser("bridge", help="SSH extract from the Brave host → inject into sandbox")
    p_bridge.add_argument("--domain", required=True, help="Cookie domain")
    p_bridge.add_argument("--host", default=SSH_HOST, help=f"SSH host (default: {SSH_HOST}, override with BRAVE_SSH_HOST)")
    p_bridge.add_argument("--container", default=CONTAINER, help=f"Docker container (default: {CONTAINER})")
    p_bridge.add_argument("--netscape", help="Also save as Netscape format")

    p_list = sub.add_parser("list-domains", help="List cookie domains in Brave")

    args = parser.parse_args()

    if args.command == "extract":
        cookies = extract_cookies(args.domain)
        auth_names = {"SID", "HSID", "SSID", "APISID", "SAPISID", "LOGIN_INFO"}
        has_auth = any(c["name"] in auth_names for c in cookies)
        print(f"Found {len(cookies)} cookies for {args.domain}", file=sys.stderr)
        if not has_auth:
            print(f"WARNING: No auth cookies found — are you logged into {args.domain} in Brave?", file=sys.stderr)

        if args.netscape:
            write_netscape(cookies, args.netscape)
            print(f"Netscape cookies written to {args.netscape}", file=sys.stderr)
        if args.out:
            write_json(cookies, args.domain, args.out)
            print(f"JSON cookies written to {args.out}", file=sys.stderr)
        elif not args.netscape:
            print(write_json(cookies, args.domain))

    elif args.command == "bridge":
        print(f"Extracting cookies for {args.domain} from Brave on {args.host}...", file=sys.stderr)
        cookies = ssh_extract(args.domain, args.host)
        print(f"  Found {len(cookies)} cookies", file=sys.stderr)

        if not cookies:
            print("ERROR: No cookies found. Are you logged into this site in Brave?", file=sys.stderr)
            sys.exit(1)

        if args.netscape:
            write_netscape(cookies, args.netscape)
            print(f"  Netscape file: {args.netscape}", file=sys.stderr)

        print(f"Injecting into sandbox Chrome ({args.container})...", file=sys.stderr)
        result = inject_into_sandbox(cookies, args.container)
        print(f"  Result: {json.dumps(result, indent=2)}")
        print("Done! The sandbox Chrome now has the Brave cookies for this domain.", file=sys.stderr)

    elif args.command == "list-domains":
        cookies = extract_cookies(domain="", )
        from collections import Counter
        domains = Counter()
        for c in cookies:
            parts = c["domain"].lstrip(".").split(".")
            top = ".".join(parts[-2:]) if len(parts) >= 2 else c["domain"]
            domains[top] += 1
        print(f"{'Domain':40s} {'Cookies':>8s}")
        print("-" * 50)
        for domain, count in domains.most_common():
            print(f"{domain:40s} {count:8d}")


if __name__ == "__main__":
    main()
